-- Languages data
CREATE TABLE IF NOT EXISTS public.languages (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  name_native TEXT,
  dir TEXT
);

INSERT INTO public.languages (code, name, name_native, dir) VALUES
('ab', 'Abkhazian', 'аҧсуа', 'ltr'),
('aa', 'Afar', 'Afaraf', 'ltr'),
('af', 'Afrikaans', 'Afrikaans', 'ltr'),
('ak', 'Akan', 'Akan', 'ltr'),
('sq', 'Albanian', 'Shqip', 'ltr'),
('am', 'Amharic', 'አማርኛ', 'ltr'),
('ar', 'Arabic', 'العربية', 'rtl'),
('an', 'Aragonese', 'Aragonés', 'ltr'),
('hy', 'Armenian', 'Հայերեն', 'ltr'),
('as', 'Assamese', 'অসমীয়া', 'ltr'),
('av', 'Avaric', 'авар мацӀ, магӀарул мацӀ', 'ltr'),
('ae', 'Avestan', 'avesta', 'ltr'),
('ay', 'Aymara', 'aymar aru', 'ltr'),
('az', 'Azerbaijani', 'azərbaycan dili', 'ltr'),
('bm', 'Bambara', 'bamanankan', 'ltr'),
('ba', 'Bashkir', 'башҡорт теле', 'ltr'),
('eu', 'Basque', 'euskara, euskera', 'ltr'),
('be', 'Belarusian', 'Беларуская', 'ltr'),
('bn', 'Bengali', 'বাংলা', 'ltr'),
('bh', 'Bihari', 'भोजपुरी', 'ltr'),
('bi', 'Bislama', 'Bislama', 'ltr'),
('bs', 'Bosnian', 'bosanski jezik', 'ltr'),
('br', 'Breton', 'brezhoneg', 'ltr'),
('bg', 'Bulgarian', 'български език', 'ltr'),
('my', 'Burmese', 'ဗမာစာ', 'ltr'),
('ca', 'Catalan; Valencian', 'Català', 'ltr'),
('ch', 'Chamorro', 'Chamoru', 'ltr'),
('ce', 'Chechen', 'нохчийн мотт', 'ltr'),
('ny', 'Chichewa; Chewa; Nyanja', 'chiCheŵa, chinyanja', 'ltr'),
('zh', 'Chinese', '中文 (Zhōngwén), 汉语, 漢語', 'ltr'),
('cv', 'Chuvash', 'чӑваш чӗлхи', 'ltr'),
('kw', 'Cornish', 'Kernewek', 'ltr'),
('co', 'Corsican', 'corsu, lingua corsa', 'ltr'),
('cr', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'ltr'),
('hr', 'Croatian', 'hrvatski', 'ltr'),
('cs', 'Czech', 'česky, čeština', 'ltr'),
('da', 'Danish', 'dansk', 'ltr'),
('dv', 'Divehi; Dhivehi; Maldivian;', 'ދިވެހި', 'rtl'),
('nl', 'Dutch', 'Nederlands, Vlaams', 'ltr'),
('en', 'English', 'English', 'ltr'),
('eo', 'Esperanto', 'Esperanto', 'ltr'),
('et', 'Estonian', 'eesti, eesti keel', 'ltr'),
('ee', 'Ewe', 'Eʋegbe', 'ltr'),
('fo', 'Faroese', 'føroyskt', 'ltr'),
('fj', 'Fijian', 'vosa Vakaviti', 'ltr'),
('fi', 'Finnish', 'suomi, suomen kieli', 'ltr'),
('fr', 'French', 'français', 'ltr'),
('ff', 'Fula; Fulah; Pulaar; Pular', 'Fulfulde, Pulaar, Pular', 'ltr'),
('gl', 'Galician', 'Galego', 'ltr'),
('ka', 'Georgian', 'ქართული', 'ltr'),
('de', 'German', 'Deutsch', 'ltr'),
('el', 'Greek, Modern', 'Ελληνικά', 'ltr'),
('gn', 'Guaraní', 'Avañeẽ', 'ltr'),
('gu', 'Gujarati', 'ગુજરાતી', 'ltr'),
('ht', 'Haitian; Haitian Creole', 'Kreyòl ayisyen', 'ltr'),
('ha', 'Hausa', 'Hausa, هَوُسَ', 'ltr'),
('he', 'Hebrew', 'עברית', 'rtl'),
('iw', 'Hebrew', 'עברית', 'rtl'),
('hz', 'Herero', 'Otjiherero', 'ltr'),
('hi', 'Hindi', 'हिन्दी, हिंदी', 'ltr'),
('ho', 'Hiri Motu', 'Hiri Motu', 'ltr'),
('hu', 'Hungarian', 'Magyar', 'ltr'),
('ia', 'Interlingua', 'Interlingua', 'ltr'),
('id', 'Indonesian', 'Bahasa Indonesia', 'ltr'),
('ie', 'Interlingue', 'Originally called Occidental; then Interlingue after WWII', 'ltr'),
('ga', 'Irish', 'Gaeilge', 'ltr'),
('ig', 'Igbo', 'Asụsụ Igbo', 'ltr'),
('ik', 'Inupiaq', 'Iñupiaq, Iñupiatun', 'ltr'),
('io', 'Ido', 'Ido', 'ltr'),
('is', 'Icelandic', 'Íslenska', 'ltr'),
('it', 'Italian', 'Italiano', 'ltr'),
('iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'ltr'),
('ja', 'Japanese', '日本語 (にほんご／にっぽんご)', 'ltr'),
('jv', 'Javanese', 'basa Jawa', 'ltr'),
('kl', 'Kalaallisut, Greenlandic', 'kalaallisut, kalaallit oqaasii', 'ltr'),
('kn', 'Kannada', 'ಕನ್ನಡ', 'ltr'),
('kr', 'Kanuri', 'Kanuri', 'ltr'),
('ks', 'Kashmiri', 'कश्मीरी, كشميري‎', 'ltr'),
('kk', 'Kazakh', 'Қазақ тілі', 'ltr'),
('km', 'Khmer', 'ភាសាខ្មែរ', 'ltr'),
('ki', 'Kikuyu, Gikuyu', 'Gĩkũyũ', 'ltr'),
('rw', 'Kinyarwanda', 'Ikinyarwanda', 'ltr'),
('ky', 'Kirghiz, Kyrgyz', 'кыргыз тили', 'ltr'),
('kv', 'Komi', 'коми кыв', 'ltr'),
('kg', 'Kongo', 'KiKongo', 'ltr'),
('ko', 'Korean', '한국어 (韓國語), 조선말 (朝鮮語)', 'ltr'),
('ku', 'Kurdish', 'Kurdî, كوردی‎', 'rtl'),
('kj', 'Kwanyama, Kuanyama', 'Kuanyama', 'ltr'),
('la', 'Latin', 'latine, lingua latina', 'ltr'),
('lb', 'Luxembourgish, Letzeburgesch', 'Lëtzebuergesch', 'ltr'),
('lg', 'Luganda', 'Luganda', 'ltr'),
('li', 'Limburgish, Limburgan, Limburger', 'Limburgs', 'ltr'),
('ln', 'Lingala', 'Lingála', 'ltr'),
('lo', 'Lao', 'ພາສາລາວ', 'ltr'),
('lt', 'Lithuanian', 'lietuvių kalba', 'ltr'),
('lu', 'Luba-Katanga', 'Kiluba', 'ltr'),
('lv', 'Latvian', 'latviešu valoda', 'ltr'),
('gv', 'Manx', 'Gaelg, Gailck', 'ltr'),
('mk', 'Macedonian', 'македонски јазик', 'ltr'),
('mg', 'Malagasy', 'Malagasy fiteny', 'ltr'),
('ms', 'Malay', 'bahasa Melayu, بهاس ملايو‎', 'ltr'),
('ml', 'Malayalam', 'മലയാളം', 'ltr'),
('mt', 'Maltese', 'Malti', 'ltr'),
('mi', 'Māori', 'te reo Māori', 'ltr'),
('mr', 'Marathi (Marāṭhī)', 'मराठी', 'ltr'),
('mh', 'Marshallese', 'Kajin M̧ajeļ', 'ltr'),
('mn', 'Mongolian', 'монгол', 'ltr'),
('na', 'Nauru', 'Ekakairũ Naoero', 'ltr'),
('nv', 'Navajo, Navaho', 'Diné bizaad, Dinékʼehǰí', 'ltr'),
('nb', 'Norwegian Bokmål', 'Norsk bokmål', 'ltr'),
('nd', 'North Ndebele', 'isiNdebele', 'ltr'),
('ne', 'Nepali', 'नेपाली', 'ltr'),
('ng', 'Ndonga', 'Owambo', 'ltr'),
('nn', 'Norwegian Nynorsk', 'Norsk nynorsk', 'ltr'),
('no', 'Norwegian', 'Norsk', 'ltr'),
('ii', 'Nuosu', 'ꆈꌠ꒿ Nuosuhxop', 'ltr'),
('nr', 'South Ndebele', 'isiNdebele', 'ltr'),
('oc', 'Occitan', 'Occitan', 'ltr'),
('oj', 'Ojibwe, Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'ltr'),
('cu', 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'ѩзыкъ словѣньскъ', 'ltr'),
('om', 'Oromo', 'Afaan Oromoo', 'ltr'),
('or', 'Oriya', 'ଓଡ଼ିଆ', 'ltr'),
('os', 'Ossetian, Ossetic', 'ирон æвзаг', 'ltr'),
('pa', 'Panjabi, Punjabi', 'ਪੰਜਾਬੀ, پنجابی‎', 'ltr'),
('pi', 'Pāli', 'पाऴि', 'ltr'),
('fa', 'Persian', 'فارسی', 'rtl'),
('pl', 'Polish', 'polski', 'ltr'),
('ps', 'Pashto, Pushto', 'پښتو', 'ltr'),
('pt', 'Portuguese', 'Português', 'ltr'),
('qu', 'Quechua', 'Runa Simi, Kichwa', 'ltr'),
('rm', 'Romansh', 'rumantsch grischun', 'ltr'),
('rn', 'Kirundi', 'kiRundi', 'ltr'),
('ro', 'Romanian', 'română', 'ltr'),
('ru', 'Russian', 'русский язык', 'ltr'),
('sa', 'Sanskrit (Saṁskṛta)', 'संस्कृतम्', 'ltr'),
('sc', 'Sardinian', 'sardu', 'ltr'),
('sd', 'Sindhi', 'सिन्धी, سنڌي، سندھی‎', 'ltr'),
('se', 'Northern Sami', 'Davvisámegiella', 'ltr'),
('sm', 'Samoan', 'gagana faa Samoa', 'ltr'),
('sg', 'Sango', 'yângâ tî sängö', 'ltr'),
('sr', 'Serbian', 'српски језик', 'ltr'),
('gd', 'Scottish Gaelic; Gaelic', 'Gàidhlig', 'ltr'),
('sn', 'Shona', 'chiShona', 'ltr'),
('si', 'Sinhala, Sinhalese', 'සිංහල', 'ltr'),
('sk', 'Slovak', 'slovenčina', 'ltr'),
('sl', 'Slovene', 'slovenščina', 'ltr'),
('so', 'Somali', 'Soomaaliga, af Soomaali', 'ltr'),
('st', 'Southern Sotho', 'Sesotho', 'ltr'),
('es', 'Spanish; Castilian', 'español, castellano', 'ltr'),
('su', 'Sundanese', 'Basa Sunda', 'ltr'),
('sw', 'Swahili', 'Kiswahili', 'ltr'),
('ss', 'Swati', 'SiSwati', 'ltr'),
('sv', 'Swedish', 'svenska', 'ltr'),
('ta', 'Tamil', 'தமிழ்', 'ltr'),
('te', 'Telugu', 'తెలుగు', 'ltr'),
('tg', 'Tajik', 'тоҷикӣ, toğikī, تاجیکی‎', 'ltr'),
('th', 'Thai', 'ไทย', 'ltr'),
('ti', 'Tigrinya', 'ትግርኛ', 'ltr'),
('bo', 'Tibetan Standard, Tibetan, Central', 'བོད་ཡིག', 'ltr'),
('tk', 'Turkmen', 'Türkmen, Түркмен', 'ltr'),
('tl', 'Tagalog', 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔', 'ltr'),
('tn', 'Tswana', 'Setswana', 'ltr'),
('to', 'Tonga (Tonga Islands)', 'faka Tonga', 'ltr'),
('tr', 'Turkish', 'Türkçe', 'ltr'),
('ts', 'Tsonga', 'Xitsonga', 'ltr'),
('tt', 'Tatar', 'татарча, tatarça, تاتارچا‎', 'ltr'),
('tw', 'Twi', 'Twi', 'ltr'),
('ty', 'Tahitian', 'Reo Tahiti', 'ltr'),
('ug', 'Uighur, Uyghur', 'Uyƣurqə, ئۇيغۇرچە‎', 'ltr'),
('uk', 'Ukrainian', 'українська', 'ltr'),
('ur', 'Urdu', 'اردو', 'rtl'),
('uz', 'Uzbek', 'zbek, Ўзбек, أۇزبېك‎', 'ltr'),
('ve', 'Venda', 'Tshivenḓa', 'ltr'),
('vi', 'Vietnamese', 'Tiếng Việt', 'ltr'),
('vo', 'Volapük', 'Volapük', 'ltr'),
('wa', 'Walloon', 'Walon', 'ltr'),
('cy', 'Welsh', 'Cymraeg', 'ltr'),
('wo', 'Wolof', 'Wollof', 'ltr'),
('fy', 'Western Frisian', 'Frysk', 'ltr'),
('xh', 'Xhosa', 'isiXhosa', 'ltr'),
('yi', 'Yiddish', 'ייִדיש', 'ltr'),
('yo', 'Yoruba', 'Yorùbá', 'ltr'),
('za', 'Zhuang, Chuang', 'Saɯ cueŋƅ, Saw cuengh', 'ltr')
ON CONFLICT (code) DO NOTHING;

